wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1633880770
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 1
      - 7
      - 13
      4: 3.8.10
      5: 0.12.4
      8:
      - 2
      - 5
