wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1633207136
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 1
      - 7
      - 13
      4: 3.8.10
      5: 0.12.3
      8:
      - 2
      - 5
accumulate_grad_batches:
  desc: null
  value: 1
classification:
  desc: null
  value: true
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
model_name:
  desc: null
  value: eca_nfnet_l0
wd:
  desc: null
  value: 0.0001
