accumulate_grad_batches: 1
classification: true
cutmix: true
cutmix_alpha: 0.5
cutmix_p: 0.5
drop_path_rate: 0.25
drop_rate: 0.25
epochs: 10
lr: 0.0001
mixup: false
mixup_alpha: 3.0
mixup_p: 0.5
model_name: resnet34d
wd: 0.0001
